#!/bin/sh
export LD_LIBRARY_PATH=/opt/odin/lib:/opt/libs/std-c++-libs:/opt/libs/nss:/opt/libs:/opt/webengine/lib:/opt/webengine/opera_dir/uva_backends:/opt/webengine/opera_dir/uva_drm_backends:/vendor/lib/utopia/mi_ipc_client:/vendor/lib/utopia:/vendor/lib/appipc:/basic/lib:/vendor/lib:/vendor/lib/WVCENC:/vendor/lib/playready:/opt/mmlib:/mtd_apexe/board/lib:/mtd_apexe/board/lib/dfb:/mtd_apexe/board/lib/atsc:/mtd_apexe/board/lib/nlib:/mtd_apexe/board/lib/libs:/mtd_apexe/board/lib/client:/mtd_apexe/board/com.nvt.nflx/lib:/mtd_apexe/board/com.nvt.ntts/lib:/usr/local/lib:/mslib
unset LD_PRELOAD
if [ "${1-}" = '--inner-timing' ]; then
    shift
    exec /tmp/moonlight-capture-timing "$@"
fi
exec /tmp/moonlight-capture "$@"
